### ISSUE TITLE
Server refuses to start

### ISSUE THREAD

**Issue by LessThanBenji** [VazkiiMods/crucial2#300]
Hi, I'm not 100% this is an issue with the Crucial 2 modpack itself so I might look like a total idiot here, but it's only happening to me when I try to launch this modpack as a Forge server so I wasn't sure where else to ask for help. Whenever I try to start the server, I get the error shown in the log I attached. This is still the initial setup stage; the modpack has installed itself, but I can't get the Forge jar to run and generate the EULA, etc..

Any help would be greatly appreciated, I can't for the life of me figure this out.

[latest.log](https://github.com/VazkiiMods/crucial2/files/7896863/latest.log)

**Comment by Hubry** [comment]
Downgrade Java to u308. You can download it from Eclipse Adoptium's [release archives](https://adoptium.net/archive.html?variant=openjdk8). You can just download the JRE zip (under the binary column), unzip it somewhere, and launch the server by pointing the to `java.exe` located there instead of using the global `java`.

 The cause is https://github.com/McModLauncher/modlauncher/issues/91, btw

**Comment by LessThanBenji** [comment]
works perfect, thanks!
